ALTER TABLE TB_FORNECEDOR ADD CONSTRAINT CK_STATUS_FORNEC
	CHECK (STATUS IN ('A','I'));

ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT CK_STATUS_FUNC
	CHECK (STATUS IN ('A','I'));

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CK_STATUS_CLI
	CHECK (STATUS IN ('A','I'));
	
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT CK_STATUS_EST
	CHECK (STATUS IN ('A','I'));
	
/*A = AGUARDANDO E = ENTREGUE AR = AGUARDANDO RETIRADA*/
ALTER TABLE TB_PEDIDOS ADD CONSTRAINT CK_STATUS_PED
	CHECK (PED_STATUS IN ('A','E','AR'));

/*S=SIM N=NÃO*/
ALTER TABLE TB_PEDIDOS ADD CONSTRAINT CK_DELIVERY
	CHECK (DELIVERY IN ('S','N'));

ALTER TABLE TB_FMA_PAGTO ADD CONSTRAINT CK_STATUS_PAGTO
	CHECK (STATUS IN ('A','N'));

	
ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT CK_ITEM_CANCEL
	CHECK (ITEM_CANCEL IN ('S','N'));
	
ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT CK_ITEM_CONFIRMADO
	CHECK (CONFIRMADO IN ('S','N'));
	
/*C=COMANDA M=MESA D=DELIVERY*/
ALTER TABLE TB_CARTAO_PEDIDO ADD CONSTRAINT CK_TIPO_CARTAO
	CHECK (TIPO IN ('C','M','D'));

/*L = LIVRE O=OCOUPADO*/
ALTER TABLE TB_CARTAO_PEDIDO ADD CONSTRAINT CK_STATUS_CARTAO 
	CHECK (STATUS IN ('L','O'));
	
ALTER TABLE TB_COZINHA ADD CONSTRAINT CK_PED_CONFIRMADO
	CHECK (CONFIRMADO IN ('S','N'));
	
ALTER TABLE TB_DELIVERY ADD CONSTRAINT CK_PED_ENTREGUE
	CHECK (ENTREGUE IN ('S','N'));

/*C=CRÉDITO D=DÉIBTO*/
ALTER TABLE TB_MOVDIARIO ADD CONSTRAINT CK_TIPMOVTO
	CHECK(TIP_MOVTO IN ('C','D'));

/*A=AUTORIZADA P=PENDENTE C=CANCELADA*/
ALTER TABLE TB_NFVENDA ADD CONSTRAINT CK_STATUS_NF
	CHECK (STATUS IN ('A','P','C'));

ALTER TABLE TB_NFVENDA ADD CONSTRAINT CK_VLRDESC
	CHECK(VLR_DESC > 0);

ALTER TABLE TB_NFVENDA ADD CONSTRAINT CK_VLRACRES
	CHECK(VLR_ACRES > 0);

ALTER TABLE TB_NFVENDA ADD CONSTRAINT CK_VLRTOTAL
	CHECK(VLR_TOTAL > 0);
	
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT CK_PRC_VENDA
	CHECK(PRC_VENDA > 0);
	
ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT CK_VLRUNIT_PED
	CHECK(VLR_UNIT > 0);

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT CK_VLRTOT_PED
	CHECK(VLR_TOTAL > 0);

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT CK_VLRDESC_PED
	CHECK(VLR_DESC > 0);

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT CK_VLRACRES_PED
	CHECK(VLR_ACRE > 0);
	
ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT CK_VLR_UNIITEM
	CHECK (VLR_UNIT > 0);

ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT CK_VLR_DESCITEM
	CHECK (VLR_DESC > 0);

ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT CK_VLR_ACRESITEM
	CHECK (VLR_ACRES > 0);

ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT CK_VLR_TOTITEM
	CHECK (VLR_TOTAL > 0);