CREATE SCHEMA AULA;
USE AULA;


CREATE TABLE IF NOT EXISTS  TB_EMITENTE (
	NOME VARCHAR(150) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	CNPJ VARCHAR(14) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	LOGRADOURO VARCHAR(150) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	BAIRRO VARCHAR(150) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	COMPLEMENTO VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	CEP CHAR(7) NOT NULL,
	EMAIL VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	SITE VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI
	);
	

CREATE TABLE IF NOT EXISTS  TB_CIDADE_SIS (
	CEP CHAR(7) PRIMARY KEY NOT NULL,
	NOME VARCHAR(30) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	SIGLA_UF CHAR(2),
	DDD CHAR(2),
	REGIAO VARCHAR(12) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI
);

CREATE TABLE IF NOT EXISTS  TB_FORNECEDOR ( 
	ID_FORNEC INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(150) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	CNPJ VARCHAR(14) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	STATUS CHAR(1) DEFAULT 'A' NOT NULL,	
	LOGRADOURO VARCHAR(150) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	BAIRRO VARCHAR(150) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	COMPLEMENTO VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	CEP CHAR(7) NOT NULL,
	DDD_COMER CHAR(2),	
	FONE_COMER VARCHAR(13) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	DDD_CELUL CHAR(2),
	FONE_CELUL VARCHAR(13) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	OBS VARCHAR(250) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	EMAIL VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI
	);

CREATE TABLE IF NOT EXISTS  TB_FUNCIONARIO (
    ID_FUNCIONARIO INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CARGO INT UNSIGNED NOT NULL,
    NOME VARCHAR(100) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
    APELIDO VARCHAR(20) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    OBS VARCHAR(250) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    STATUS CHAR(1) DEFAULT 'A' NOT NULL,
    BAIRRO VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    LOGRADOURO VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    COMPLEMENTO VARCHAR(45) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    EMAIL_CONTATO VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    CPF VARCHAR(11) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
    RG VARCHAR(16) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
    CEP VARCHAR(8) NOT NULL,
    NUMERO VARCHAR(5) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    DDD_CELUL CHAR(2),
    FONE_CELUL VARCHAR(16) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    DT_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP
    );
   
CREATE TABLE IF NOT EXISTS  TB_CARGO (
	ID_CARGO INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI
	);

CREATE TABLE IF NOT EXISTS  TB_CLIENTE (
    ID_CLIENTE INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(80) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	DDD_COMER CHAR(2),	
	FONE_COMER VARCHAR(13) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	DDD_CELUL CHAR(2),
	FONE_CELUL VARCHAR(13) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,    
	LOGRADOURO VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	BAIRRO VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	COMPLEMENTO VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	CEP CHAR(7),
	STATUS CHAR(1) DEFAULT 'A' NOT NULL,
	OBS VARCHAR(250) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	EMAIL VARCHAR(150) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
    LIMITE_CREDITO NUMERIC(18,2),
    DT_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VLR_CREDITO NUMERIC(18,4),
    DT_PRIM_COMP DATETIME,
    DT_ULT_COMP DATETIME
	);

CREATE TABLE IF NOT EXISTS  TB_CLI_PJ (
    ID_CLIENTE INT UNSIGNED NOT NULL, 
    CNPJ VARCHAR(18) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI 
    );
      
CREATE TABLE IF NOT EXISTS  TB_CLI_PF (
    ID_CLIENTE INT UNSIGNED NOT NULL, 
    CPF VARCHAR(14) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI 
    );


CREATE TABLE IF NOT EXISTS  TB_ESTOQUE (
	ID_ESTOQUE INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_GRUPO INT UNSIGNED,
	DESCRICAO VARCHAR (60) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	UNI_MEDIDA CHAR(3) NOT NULL,
	QTD_ATUAL NUMERIC(18,4) NOT NULL DEFAULT '0',
	PRC_VENDA NUMERIC(18,4) NOT NULL DEFAULT '0',
	QTD_MINIM NUMERIC(18,4),
	FOTO BLOB,
	COD_BARRA VARCHAR(18) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	REFERENCIA VARCHAR(18) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	DESC_COMPL VARCHAR(25) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	OBS VARCHAR(250) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	DT_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
	DT_ULT_VENDA DATETIME DEFAULT CURRENT_TIMESTAMP,
	STATUS CHAR(1) DEFAULT 'A'
	);

CREATE TABLE IF NOT EXISTS TB_UNI_MEDIDA (
	UNI_MEDIDA CHAR(3) PRIMARY KEY NOT NULL,
	DESCRICAO VARCHAR(100) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI,
	CONVERSOR NUMERIC(18,4)
	);

CREATE TABLE IF NOT EXISTS  TB_GRUPO ( 
	ID_GRUPO INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(30) CHARACTER SET UTF8MB4 NOT NULL COLLATE UTF8MB4_UNICODE_CI
	);

CREATE TABLE IF NOT EXISTS TB_PEDIDOS (
	ID_PEDIDO INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_CLIENTE INT UNSIGNED NOT NULL DEFAULT '0',
	PED_STATUS VARCHAR(2) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI, 
	DT_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
	OCUPANTES SMALLINT DEFAULT 1 NOT NULL,
	DT_ENTREGA DATETIME,	
	DELIVERY CHAR(1)
	);
	
CREATE TABLE IF NOT EXISTS TB_PEDIDO_ITEM (
	ID_PED_ITEM INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
	ID_PEDIDO INT UNSIGNED NOT NULL,
	ID_ESTOQUE INT UNSIGNED NOT NULL,
	ID_VENDEDOR INT UNSIGNED NOT NULL,
	ITEM_CANCEL CHAR(1),
	CONFIRMADO CHAR(1), 
	QTD_ITEM NUMERIC(18,4),
	VLR_UNIT NUMERIC(18,4),
	VLR_TOTAL NUMERIC(18,4),
	VLR_DESC NUMERIC(18,4),
	VLR_ACRE NUMERIC(18,4),
	OBS VARCHAR(250) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI
	);
	
CREATE TABLE IF NOT EXISTS TB_CARTAO_PEDIDO (
	ID_CARTAO INT UNSIGNED PRIMARY KEY NOT NULL,
	ID_PEDIDO INT UNSIGNED,
	DESCRICAO VARCHAR(14) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	TIPO CHAR(1),
	STATUS CHAR(1),
	DT_CARTAO DATETIME DEFAULT CURRENT_TIMESTAMP
	); 

CREATE TABLE IF NOT EXISTS TB_COZINHA (
	ID_COZINHA INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_COZINHEIRA INT UNSIGNED NOT NULL,
	ID_PEDIDO INT UNSIGNED NOT NULL,
	CONFIRMADO CHAR(1)
	);

CREATE TABLE IF NOT EXISTS TB_DELIVERY (
	ID_PEDIDO INT UNSIGNED NOT NULL,
	ID_CLIENTE INT UNSIGNED NOT NULL,	
	ID_FMAPAGTO INT UNSIGNED NOT NULL,
	DT_SAIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
	DT_ENTREGA DATETIME,
	ENTREGUE CHAR(1)
	);

CREATE TABLE IF NOT EXISTS TB_FMA_PAGTO (
	ID_FMAPAGTO INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(40) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	STATUS CHAR(1) DEFAULT 'A'
	);

CREATE TABLE IF NOT EXISTS TB_MOVDIARIO (
	ID_MOVTO INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_FMAPAGTO INT UNSIGNED NOT NULL, 
	DT_MOVTO DATETIME DEFAULT CURRENT_TIMESTAMP,
	HISTORICO VARCHAR(60) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI,
	TIP_MOVTO CHAR(1),
	VLR_MOVTO NUMERIC(18,4)
	);

CREATE TABLE IF NOT EXISTS TB_NFVENDA (
	ID_NFVENDA INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NF_NUMERO INT UNSIGNED NOT NULL,
	ID_CLIENTE INT UNSIGNED NOT NULL,
	ID_CIDADE CHAR(7),
	ID_FMAPAGTO INT UNSIGNED NOT NULL,
	STATUS CHAR(1),
	VLR_TOTAL NUMERIC(18,4),
	VLR_DESC NUMERIC(18,4),
	VLR_ACRES NUMERIC(18,4),
	OBS VARCHAR(250) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI
	);

CREATE TABLE IF NOT EXISTS TB_NFV_ITEM (
	ID_NFVITEM INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_NFVENDA INT UNSIGNED NOT NULL,
	ID_ESTOQUE INT UNSIGNED NOT NULL,
	UNI_MEDIDA CHAR(3) NOT NULL,
	VLR_UNIT NUMERIC(18,4),
	VLR_DESC NUMERIC(18,4),
	VLR_ACRES NUMERIC(18,4),
	VLR_TOTAL NUMERIC(18,4)
	);

CREATE TABLE IF NOT EXISTS TB_PED_VENDA (
	ID_PEDIDO INT UNSIGNED NOT NULL,
	ID_NFVENDA INT UNSIGNED NOT NULL
	);

CREATE TABLE IF NOT EXISTS TB_PED_VENDA_ITEM (
	ID_PED_ITEM INT UNSIGNED NOT NULL,
	ID_NFVITEM INT UNSIGNED NOT NULL
	);
	
