ALTER TABLE TB_FORNECEDOR ADD CONSTRAINT FK_CIDADE_FORNEC
	FOREIGN KEY(CEP)
	REFERENCES TB_CIDADE_SIS(CEP);

ALTER TABLE TB_EMITENTE ADD CONSTRAINT FK_ID_CIDADE_EMITENTE
	FOREIGN KEY(CEP)
	REFERENCES TB_CIDADE_SIS(CEP);
	
ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT FK_ID_CIDADE_FUNC
	FOREIGN KEY(CEP)
	REFERENCES TB_CIDADE_SIS(CEP);
	
ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT FK_CARGO_FUNC
	FOREIGN KEY(ID_CARGO)
	REFERENCES TB_CARGO(ID_CARGO);
	
ALTER TABLE TB_CLIENTE ADD CONSTRAINT FK_CIDADE_CLI
	FOREIGN KEY(CEP)
	REFERENCES TB_CIDADE_SIS(CEP);
	
ALTER TABLE TB_CLI_PJ ADD CONSTRAINT FK_CLI_PJ
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES TB_CLIENTE(ID_CLIENTE);
	
ALTER TABLE TB_CLI_PF ADD CONSTRAINT FK_CLI_PF
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES TB_CLIENTE(ID_CLIENTE);
	
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT FK_GRUPO_EST
	FOREIGN KEY(ID_GRUPO)
	REFERENCES TB_GRUPO(ID_GRUPO);
	
ALTER TABLE TB_PEDIDOS ADD CONSTRAINT FK_CLIENTE_PED
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES TB_CLIENTE(ID_CLIENTE);

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_ID_PEDIDO
	FOREIGN KEY(ID_PEDIDO)
	REFERENCES TB_PEDIDOS(ID_PEDIDO);

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_ITEM_PEDIDO
	FOREIGN KEY(ID_ESTOQUE)
	REFERENCES TB_ESTOQUE(ID_ESTOQUE);

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_VENDEDOR_ITEM
	FOREIGN KEY(ID_VENDEDOR)
	REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO);

ALTER TABLE TB_CARTAO_PEDIDO ADD CONSTRAINT FK_PEDIDO_CART
	FOREIGN KEY (ID_PEDIDO)
	REFERENCES TB_PEDIDOS(ID_PEDIDO);

ALTER TABLE TB_COZINHA ADD CONSTRAINT FK_COZINHEIRA
	FOREIGN KEY (ID_COZINHEIRA)
	REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO);

ALTER TABLE TB_COZINHA ADD CONSTRAINT FK_PED_COZINHA
	FOREIGN KEY (ID_PEDIDO)
	REFERENCES TB_PEDIDOS (ID_PEDIDO);
	
ALTER TABLE TB_DELIVERY ADD CONSTRAINT FK_ID_PED_DELIVERY
	FOREIGN KEY (ID_PEDIDO)
	REFERENCES TB_PEDIDOS(ID_PEDIDO);

ALTER TABLE TB_DELIVERY ADD CONSTRAINT FK_ID_CLIENTE_DELIVERY
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES TB_CLIENTE(ID_CLIENTE);
	
ALTER TABLE TB_DELIVERY ADD CONSTRAINT FK_PAGTO_DELIVERY
	FOREIGN KEY (ID_FMAPAGTO)
	REFERENCES TB_FMA_PAGTO(ID_FMAPAGTO);
	
ALTER TABLE TB_MOVDIARIO ADD CONSTRAINT FK_IDFMAPAGTO
	FOREIGN KEY (ID_FMAPAGTO)
	REFERENCES TB_FMA_PAGTO(ID_FMAPAGTO);

ALTER TABLE TB_NFVENDA ADD CONSTRAINT FK_ID_CLIENTENF
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES TB_CLIENTE(ID_CLIENTE);

ALTER TABLE TB_NFVENDA ADD CONSTRAINT FK_ID_CIDADENF
	FOREIGN KEY(ID_CIDADE)
	REFERENCES TB_CIDADE_SIS(CEP);

ALTER TABLE TB_NFVENDA ADD CONSTRAINT FK_ID_FMPAGTONF
	FOREIGN KEY(ID_FMAPAGTO)
	REFERENCES TB_FMA_PAGTO(ID_FMAPAGTO);
	
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT FK_UNI_MEDIDA
	FOREIGN KEY (UNI_MEDIDA)
	REFERENCES TB_UNI_MEDIDA(UNI_MEDIDA);
	
ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT FK_ID_NFVENDAITEM
	FOREIGN KEY (ID_NFVENDA)
	REFERENCES TB_NFVENDA(ID_NFVENDA);

ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT FK_ID_ESTOQUENF
	FOREIGN KEY(ID_ESTOQUE)
	REFERENCES TB_ESTOQUE(ID_ESTOQUE);

ALTER TABLE TB_NFV_ITEM ADD CONSTRAINT FK_UNI_MEDIDANF
	FOREIGN KEY(UNI_MEDIDA)
	REFERENCES TB_UNI_MEDIDA(UNI_MEDIDA);
	
ALTER TABLE TB_PED_VENDA ADD CONSTRAINT FK_ID_PED_VENDA
	FOREIGN KEY (ID_PEDIDO)
	REFERENCES TB_PEDIDOS(ID_PEDIDO);

ALTER TABLE TB_PED_VENDA ADD CONSTRAINT FK_ID_VENDA_PED
	FOREIGN KEY (ID_NFVENDA)
	REFERENCES TB_NFVENDA(ID_NFVENDA);
	
ALTER TABLE TB_PED_VENDA_ITEM ADD CONSTRAINT FK_ITEM_PED_VENDA
	FOREIGN KEY(ID_PED_ITEM)
	REFERENCES TB_PEDIDO_ITEM(ID_PED_ITEM);

ALTER TABLE TB_PED_VENDA_ITEM ADD CONSTRAINT FK_ITEM_VENDA_PED
	FOREIGN KEY(ID_NFVITEM)
	REFERENCES TB_NFV_ITEM(ID_NFVITEM);