CREATE VIEW V_CARDAPIO AS 
SELECT
	TES.ID_ESTOQUE  AS COD_ITEM,
	TES.DESCRICAO AS PRATO,
	TES.PRC_VENDA AS VALOR
FROM TB_ESTOQUE TES
WHERE TES.STATUS = 'A' 
	AND TES.QTD_ATUAL > 0 
		AND TES.PRC_VENDA IS NOT NULL;
		
 
CREATE VIEW V_PEDIDOS AS 
SELECT
	TP.ID_PEDIDO,
	CASE 
		WHEN TCP.TIPO = 'C' THEN 'Comanda'
		WHEN TCP.TIPO = 'M' THEN 'Mesa'
		WHEN TCP.TIPO = 'D' THEN 'Delivery'
	END AS CARTAO,
	CASE 
		WHEN TP.PED_STATUS = 'E' THEN 'Entregue'
		WHEN TP.PED_STATUS = 'A' THEN 'Aguardando'
		WHEN TP.PED_STATUS = 'AR' THEN 'Aguardando retirada'
	END AS STATUS,
	TP.DT_PEDIDO,
	TC.NOME,
	COALESCE(PF.CPF,PJ.CNPJ) AS CPF_CNPJ,
	'(' || TC.DDD_CELUL || ')' || TC.FONE_CELUL AS CELULAR,
	TC.LOGRADOURO,
	TC.BAIRRO ,
	TC.COMPLEMENTO,
	TC.CEP,
	TC.EMAIL
FROM TB_PEDIDOS TP
	LEFT JOIN TB_CLIENTE TC ON
		TC.ID_CLIENTE  = TP.ID_CLIENTE 
	LEFT JOIN TB_CLI_PF PF ON 
		PF.ID_CLIENTE  = TC.ID_CLIENTE 
	LEFT JOIN TB_CLI_PJ PJ ON 
		PJ.ID_CLIENTE  = TC.ID_CLIENTE
	LEFT JOIN TB_CARTAO_PEDIDO TCP ON 
		TCP.ID_PEDIDO  = TP.ID_PEDIDO; 
	
CREATE VIEW V_COZINHA_PED AS 
SELECT
	TF.NOME AS COZINHEIRA,
	TE.DESCRICAO,
	TPI.QTD_ITEM,
	TPI.VLR_UNIT,
	TPI.VLR_TOTAL,
	TPI.CONFIRMADO AS CONFIRMADO_GARCOM,
	TCO.CONFIRMADO  AS CONFIRMADO_COZINHA
FROM TB_COZINHA TCO
	LEFT JOIN TB_PEDIDOS TP ON 
		TP.ID_PEDIDO = TCO.ID_PEDIDO
	LEFT JOIN TB_PEDIDO_ITEM TPI ON 
		TPI.ID_PEDIDO  = TP.ID_PEDIDO 
	LEFT JOIN TB_FUNCIONARIO TF ON 
		TF.ID_FUNCIONARIO  = TCO.ID_COZINHEIRA 
	LEFT JOIN TB_ESTOQUE TE ON 
		TE.ID_ESTOQUE = TPI.ID_ESTOQUE 
WHERE TPI.ITEM_CANCEL <> 'N';
		
CREATE VIEW V_CONTROLEMESA AS 
SELECT
	TP.ID_PEDIDO,
	TP.DT_PEDIDO,
	TCP.ID_CARTAO AS MESA_COMANDA,
	TP.OCUPANTES,
	TP.PED_STATUS AS STATUS
FROM TB_PEDIDOS TP 
	LEFT JOIN TB_CARTAO_PEDIDO TCP ON 
		TCP.ID_PEDIDO = TP.ID_PEDIDO;
		
	

CREATE VIEW V_MOVDIARIO AS 
SELECT
	TM.ID_MOVTO,
	FMA.DESCRICAO,
	TM.DT_MOVTO, 
	TM.HISTORICO,
	CASE WHEN TM.TIP_MOVTO = 'C' THEN TM.VLR_MOVTO ELSE 0 END,
	CASE WHEN TM.TIP_MOVTO = 'D' THEN TM.VLR_MOVTO ELSE 0 END
FROM TB_MOVDIARIO TM
	LEFT JOIN (SELECT TFP.ID_FMAPAGTO, TFP.DESCRICAO FROM TB_FMA_PAGTO TFP) FMA ON
		FMA.ID_FMAPAGTO = TM.ID_FMAPAGTO;
	
	
CREATE VIEW V_NFVENDA AS 
SELECT
	NF.ID_NFVENDA,
	NF.NF_NUMERO,
	NF.STATUS,
	CLI.NOME,
	CLI.CPF_CNPJ,
	TCS.NOME AS CIDADE,
	TFP.DESCRICAO,
	NF.VLR_TOTAL,
	NF.VLR_DESC,
	NF.VLR_ACRES,
	NF.OBS
FROM TB_NFVENDA NF 
	LEFT JOIN  (SELECT TC.ID_CLIENTE, TC.NOME AS NOME, COALESCE(PJ.CNPJ,PF.CPF) AS CPF_CNPJ  FROM TB_CLIENTE TC LEFT JOIN TB_CLI_PJ PJ ON PJ.ID_CLIENTE = TC.ID_CLIENTE
		LEFT JOIN TB_CLI_PF PF ON PF.ID_CLIENTE = TC.ID_CLIENTE) CLI ON 
			CLI.ID_CLIENTE = NF.ID_CLIENTE 
	LEFT JOIN (SELECT SIS.CEP, SIS.NOME FROM TB_CIDADE_SIS SIS) TCS ON 
		TCS.CEP = NF.ID_CIDADE 
	LEFT JOIN (SELECT PAG.ID_FMAPAGTO, PAG.DESCRICAO FROM TB_FMA_PAGTO PAG) TFP ON 
		TFP.ID_FMAPAGTO = NF.ID_FMAPAGTO; 
		
	
	


